application: appname
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(html|js|css|gif|png|jpg|xml|json|txt|ico))
  static_files: _site/\1
  upload: _site/(.*\.(html|js|css|gif|png|jpg|xml|json|txt|ico))
  
- url: /tag/(.*/?)
  static_files: _site/category/\1index.html
  upload: _site/category/(.*/?)index.html
  
- url: /(.*/)
  static_files: _site/\1index.html
  upload: _site/(.*/)index.html
  
- url: /
  static_files: _site/index.html
  upload: _site/index.html